### ISSUE TITLE
NERDTree always shows line numbers

### ISSUE THREAD

**Issue by AdamWhittingham** [jeffkreeftmeijer/vim-numbertoggle#19]
Hi,

NERDTree no longer honours the setting for hiding line numbers. I tried adding `let nerdtreeshowlinenumbers=0` to the end of the update function to no avail. Is there an easy way to make NERDTree exempt from showing the line numbers please?

Thanks for a neat plugin!

**Comment by Leandros** [comment]
Reappeared with 2.0 update.

**Comment by jeffkreeftmeijer** [comment]
Instead of adding exceptions for tools like NERDTree, I'd like numbertoggle to disable itself automatically in buffers without line numbers. This means users would have to set `number` and `relativenumber` in their ~/.vimrc files themselves, which I think would be acceptable.

I opened a pull request in #38 to disable numbertoggle automatically when `number` is not set, which works for me in Goyo. @Leandros since I don't have NERDTree installed, could you switch your install to the `if-number` branch to check if this fix works with NERDTree as well?

**Comment by Leandros** [comment]
Yes, seems to work. NERDTree isn't showing line-numbers anymore after switching to it.
