### ISSUE TITLE
Does not switch back to relative when exiting insert mode with ^C

### ISSUE THREAD

**Issue by RatanRSur** [jeffkreeftmeijer/vim-numbertoggle#30]

**Comment by googlebleh** [comment]
Why was this issue closed? I'm still observing this problem with the latest version.

**Comment by RatanRSur** [comment]
I think ^C does not actually allow the plugin to do anything, taking you back to insert mode immediately.

Use:
`inoremap <C-c> <Esc>`

**Comment by jeffkreeftmeijer** [comment]
Hey both! Missed this one back in 2015. I don't use `^C` to get out of insert mode, so I never noticed this isn't working, but I can reproduce this.

Using `^C` doesn't seem to trigger the `InsertLeave` autocommand event, which is causing this. Aside from @RatanRSur's remap, I don't know how to fix it in numbertoggle, but I'd love a pull request if anyone has a great idea.

**Comment by googlebleh** [comment]
Thanks to both of you for being so responsive to an old issue!

Just to explain why @RatanRSur's suggestion alone wouldn't work for me: I use `^C` because of the [lag Esc causes](https://stackoverflow.com/a/2158610/6466133) when leaving insert mode. I'd have to also `set 'noesckeys'` in order for remapping `^C` to be sufficient. That may be find for me, but for someone else, unsetting `esckeys` may not be desirable.

So there is some practical need to find another way to hook `^C`. I'll keep an eye out for other ideas.

**Comment by AndrewRadev** [comment]
One way would be to listen to `CursorHold` and/or `CursorMoved`, both of which get triggered in normal mode and not in insert mode. But you'd have to test it out in terms of performance. A check for a global variable's value should be fast enough. Say, on every cursor move/hold, `if g:numbertoggle_mode != 'normal' | :set ... | let g:numbertoggle_mode = 'normal' | endif`

Alternatively, the plugin could `inoremap <silent> <c-c> :numbertoggle#CtrlC()<cr>`.

> That's fine for me, but someone else may not want to.

It could be an explicit setting for people to opt into. Using `<c-c>` for exiting normal mode seems like it'd be rare, so might be fine for @googlebleh and any other users to do a little bit of extra work.

**Comment by matthsims** [comment]
Using `<C-c>` to exit insert mode intentionally does not trigger the `InsertLeave` autocommand, and consequently this should not be changed. See `:h i_CTRL-C`

**Comment by jeffkreeftmeijer** [comment]
I think remapping `<c-c>` should be the best option here, but I’d rather not add that to the main plugin, as I’d prefer not to do any remapping if I don’t have to, and also because I don’t `<c-c>` to get out of insert mode.

If you do, I’d recommend @AndrewRadev’s suggestion to remap `<c-c>` yourself in your `~/.vimrc`:

    inoremap <silent> <c-c> set nornu<cr>
